import 'modelos.dart';

/// Copia local del catálogo (supabase/seed.sql). La app la usa para la cuadrícula de
/// "Reportar" y el modo demostración; las reglas que cuentan las aplica el servidor.
const List<Categoria> catalogo = [
  Categoria(
    clave: 'menor_desaparecido',
    nombre: 'Menor desaparecido o posible sustracción',
    nombreCorto: 'Menor desaparecido',
    etiqueta: 'Menor',
    nivel: 4,
    requiereValidacion: true,
    soloInstitucion: false,
    radioMaxNoConfM: 0,
    vigencia: Duration(hours: 72),
    categoriaCap: 'Rescue',
    instrucciones: 'Si lo ves, no lo pierdas de vista y llama al 911 de inmediato. No intervengas por tu cuenta.',
    escalones: [Escalon(0, 1000), Escalon(15, 3000), Escalon(60, 10000), Escalon(180, 25000)],
  ),
  Categoria(
    clave: 'persona_desaparecida',
    nombre: 'Persona desaparecida',
    nombreCorto: 'Persona desaparecida',
    etiqueta: 'Persona',
    nivel: 3,
    requiereValidacion: true,
    soloInstitucion: false,
    radioMaxNoConfM: 0,
    vigencia: Duration(hours: 72),
    categoriaCap: 'Rescue',
    instrucciones: 'Si la ves, llama al 911 e indica dónde y a qué hora. No difundas datos personales adicionales.',
    escalones: [Escalon(0, 1000), Escalon(30, 3000), Escalon(120, 10000)],
  ),
  Categoria(
    clave: 'persona_vulnerable',
    nombre: 'Adulto mayor o persona vulnerable extraviada',
    nombreCorto: 'Persona vulnerable extraviada',
    etiqueta: 'Adulto m.',
    nivel: 3,
    requiereValidacion: true,
    soloInstitucion: false,
    radioMaxNoConfM: 0,
    vigencia: Duration(hours: 48),
    categoriaCap: 'Rescue',
    instrucciones: 'Si la ves, acércate con calma, procura que esté segura y llama al 911.',
    escalones: [Escalon(0, 1000), Escalon(30, 3000), Escalon(120, 10000)],
  ),
  Categoria(
    clave: 'robo_vehiculo',
    nombre: 'Robo de vehículo',
    nombreCorto: 'Robo de vehículo',
    etiqueta: 'Vehículo',
    nivel: 3,
    requiereValidacion: false,
    soloInstitucion: false,
    radioMaxNoConfM: 1000,
    vigencia: Duration(hours: 24),
    categoriaCap: 'Security',
    instrucciones: 'Si ves el vehículo, no lo sigas ni intervengas. Anota lugar, hora y dirección, y llama al 911.',
    escalones: [Escalon(0, 3000), Escalon(20, 10000), Escalon(60, 25000)],
  ),
  Categoria(
    clave: 'asalto',
    nombre: 'Asalto o situación de riesgo',
    nombreCorto: 'Asalto o riesgo',
    etiqueta: 'Asalto',
    nivel: 3,
    requiereValidacion: false,
    soloInstitucion: false,
    radioMaxNoConfM: 1000,
    vigencia: Duration(hours: 2),
    categoriaCap: 'Security',
    instrucciones: 'Evita la zona. Si estás en peligro, ponte a salvo y llama al 911.',
    escalones: [Escalon(0, 1000), Escalon(30, 2000)],
  ),
  Categoria(
    clave: 'incendio',
    nombre: 'Incendio',
    nombreCorto: 'Incendio',
    etiqueta: 'Incendio',
    nivel: 3,
    requiereValidacion: false,
    soloInstitucion: false,
    radioMaxNoConfM: 1000,
    vigencia: Duration(hours: 6),
    categoriaCap: 'Fire',
    instrucciones: 'Aléjate del humo y no bloquees el paso a los bomberos. Si hay personas en riesgo, llama al 911.',
    escalones: [Escalon(0, 1000), Escalon(20, 3000)],
  ),
  Categoria(
    clave: 'inundacion',
    nombre: 'Inundación',
    nombreCorto: 'Inundación',
    etiqueta: 'Inundación',
    nivel: 3,
    requiereValidacion: false,
    soloInstitucion: false,
    radioMaxNoConfM: 1000,
    vigencia: Duration(hours: 12),
    categoriaCap: 'Met',
    instrucciones: 'No cruces calles inundadas a pie ni en vehículo. Busca zonas altas y sigue a Protección Civil.',
    escalones: [Escalon(0, 2000), Escalon(60, 5000)],
  ),
  Categoria(
    clave: 'accidente',
    nombre: 'Accidente o emergencia',
    nombreCorto: 'Accidente',
    etiqueta: 'Accidente',
    nivel: 2,
    requiereValidacion: false,
    soloInstitucion: false,
    radioMaxNoConfM: 1000,
    vigencia: Duration(hours: 3),
    categoriaCap: 'Transport',
    instrucciones: 'Evita la zona para no estorbar a los servicios de emergencia. Si hay heridos, llama al 911.',
    escalones: [Escalon(0, 1000)],
  ),
  Categoria(
    clave: 'riesgo_ambiental',
    nombre: 'Riesgo ambiental',
    nombreCorto: 'Riesgo ambiental',
    etiqueta: 'Ambiental',
    nivel: 2,
    requiereValidacion: false,
    soloInstitucion: false,
    radioMaxNoConfM: 1000,
    vigencia: Duration(hours: 24),
    categoriaCap: 'Env',
    instrucciones: 'Si hay humo o gases, cierra puertas y ventanas y sigue las indicaciones de Protección Civil.',
    escalones: [Escalon(0, 3000), Escalon(60, 10000)],
  ),
  Categoria(
    clave: 'otro',
    nombre: 'Otra situación de riesgo',
    nombreCorto: 'Situación de riesgo',
    etiqueta: 'Otro',
    nivel: 1,
    requiereValidacion: false,
    soloInstitucion: false,
    radioMaxNoConfM: 1000,
    vigencia: Duration(hours: 6),
    categoriaCap: 'Other',
    instrucciones: 'Mantente atento y evita riesgos innecesarios. En una emergencia, llama al 911.',
    escalones: [Escalon(0, 1000)],
  ),
  Categoria(
    clave: 'evacuacion',
    nombre: 'Evacuación',
    nombreCorto: 'Evacuación',
    etiqueta: 'Evacuación',
    nivel: 4,
    requiereValidacion: false,
    soloInstitucion: true,
    radioMaxNoConfM: 0,
    vigencia: Duration(hours: 12),
    categoriaCap: 'Safety',
    instrucciones:
        'Sigue las rutas de evacuación y las indicaciones de las autoridades. No regreses hasta que lo indiquen.',
    escalones: [Escalon(0, 2000)],
  ),
  Categoria(
    clave: 'fenomeno_natural',
    nombre: 'Fenómeno natural',
    nombreCorto: 'Fenómeno natural',
    etiqueta: 'Fenómeno',
    nivel: 4,
    requiereValidacion: false,
    soloInstitucion: true,
    radioMaxNoConfM: 0,
    vigencia: Duration(hours: 24),
    categoriaCap: 'Geo',
    instrucciones: 'Mantén la calma, sigue a Protección Civil y ten a la mano tu mochila de emergencia.',
    escalones: [Escalon(0, 10000)],
  ),
];

Categoria categoriaPorClave(String clave) => catalogo.firstWhere((c) => c.clave == clave, orElse: () => catalogo.last);
